spring:
  application:
    name: product-ms

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8082

#springdoc:
#  api-docs:
#    path: /api-docs
#  packagesToScan:

#eureka:
#  instance:
#    prefer-ip-address: false
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#  service-url:
#    defaultZone: http://localhost:8761/eureka/